default_language_version:
   python: python3
repos:
-  repo: https://github.com/ambv/black
   rev: 19.10b0
   hooks:
   - id: black
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.5.0
   hooks:
   - id: check-merge-conflict
   - id: flake8
   - id: trailing-whitespace
   - id: check-yaml
