# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - "3.7"

stages:
    - lint
    - test

jobs:
    include:
        - stage: lint
          install:
              - pip install pre-commit
              - pre-commit install-hooks
          script:
              - pre-commit run --all-files
        - stage: test
          install:
              - export TZ=America/Los_Angeles
              - pip install poetry keyrings.alt
              - poetry install -v
          script:
              - pytest -ra --cov=quare tests

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: jstvz
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: jstvz/quare
#     python: 3.7
